DROP TABLE IF EXISTS "PUBLIC"."BOOK";
CREATE CACHED TABLE "PUBLIC"."BOOK"
(
  "BOOKID"      INT          NOT NULL AUTO_INCREMENT,
  "TITLE"       VARCHAR(250) NOT NULL,
  "AUTHOR"      VARCHAR(250) NOT NULL,
  "PLEDGE"      INT          NOT NULL,
  "RENTALPRICE" INT          NOT NULL,
  "GENRE"       VARCHAR(250) NOT NULL
);
ALTER TABLE "PUBLIC"."BOOK"
  ADD CONSTRAINT "PUBLIC"."PRIMARY1" PRIMARY KEY ("BOOKID");

DROP TABLE IF EXISTS "PUBLIC"."READER";
CREATE CACHED TABLE "PUBLIC"."READER" (
  "READERID"    INT          NOT NULL AUTO_INCREMENT,
  "SURNAME"     VARCHAR(250) NOT NULL,
  "FIRSTNAME"   VARCHAR(250) NOT NULL,
  "PATRONYMIC"  VARCHAR(250),
  "HOMEADDRESS" VARCHAR(250) NOT NULL,
  "PHONENUMBER" INT          NOT NULL
);
ALTER TABLE "PUBLIC"."READER"
  ADD CONSTRAINT "PUBLIC"."PRIMARY2" PRIMARY KEY ("READERID");